BUCKET: 'tli-crm-segmentation'
PREFIX: 'data-pipeline'
PIPELINE_NAME: 'CustomerSegmentation'

INSTANCE_TYPE: 'ml.t3.2xlarge'
INSTANCE_COUNT: 1
FRAMEWORK_VERSION: '1.2-1'

STEP_PROCESSING: 'PROCESSING'
STEP_GROUPING: 'GROUPING'
STEP_CLUSTERING: 'CLUSTERING'
# STEP_EVALUATE: 'EVALUATING'
# STEP_INFERENCE: 'INFERENCING'
# STEP_PACK: 'PACKING'
# STEP_STRATEGY: 'STRATEGY'

# TRAIN_DT: '20240417'