BASEPLAN_GROUP:
    saving: ['END', 'UL', 'PENSION', 'ULTP']
    wholelife: ['WHL']
    termpa: ['PA', 'TERM', 'Term']

RIDER_GROUP:
    health: ['Hospital Benefits Rider', 'Health & Surgery Rider']
    ci: ['Critical Illness Rider']
    # accident: ['Accident Rider', 'Personal Accident']
    # accident_medical: ['Accident Medical Expense']
    # accident_death: ['Accident Death Benefit', 'Accident Death & Dismemberment']

BENEFICIARY_INPUT:
    - is_bene_parent
    - is_bene_child
    - is_bene_spouse
    
POLICY_ACTIVE_STATUS:
    - A
    - E
    - F
    - H
    - I
    - J
    - R
    - U
    - W

POLICY_REMOVE_STATUS:
    - D
    - B
    - N

RIDER_ACTIVE_STATUS:
    - N
    - S
    
PREMIUM_INPUT:
    - total_premium_saving
    - total_premium_wholelife
    - total_premium_health
    - total_premium_ci
    - total_premium
    
BENEFICIARY_GROUP:
    0: spouse
    1: parent
    2: child
    3: childspouse
    4: nofamily